import { NUMBER, SELECT, TOGGLE, TIMER } from "./InputTypes";

const ATTEMPT_DATA = { LOW: NUMBER, HIGH: NUMBER };

const SCORE_DATA = {
  LOW: NUMBER,
  OUTER: NUMBER,
  INNER: NUMBER,
};

const ATTEMPTED_DATA = {
  SECTOR: ATTEMPT_DATA,
  "TARGET ZONE": ATTEMPT_DATA,
  "CLOSE FRIENDLY TRENCH": ATTEMPT_DATA,
  "FAR FRIENDLY TRENCH": ATTEMPT_DATA,
  "CLOSE OPP TRENCH": ATTEMPT_DATA,
  "FAR OPP TRENCH": ATTEMPT_DATA,
  RENDEZVOUS: ATTEMPT_DATA,
  "BEHIND THE RENDEZVOUS": ATTEMPT_DATA,
  "IN FRONT OF THE RENDEZVOUS": ATTEMPT_DATA,
};

const SCORED_DATA = {
  SECTOR: SCORE_DATA,
  "TARGET ZONE": SCORE_DATA,
  "CLOSE FRIENDLY TRENCH": SCORE_DATA,
  "FAR FRIENDLY TRENCH": SCORE_DATA,
  "CLOSE OPP TRENCH": SCORE_DATA,
  "FAR OPP TRENCH": SCORE_DATA,
  RENDEZVOUS: SCORE_DATA,
  "BEHIND THE RENDEZVOUS": SCORE_DATA,
  "IN FRONT OF THE RENDEZVOUS": SCORE_DATA,
};

const INFINITE_RECHARGE = {
  "TEAM #": NUMBER,
  ALLIANCE: { ...SELECT, options: ["BLUE", "RED"] },
  "MATCH #": NUMBER,
  AUTO: {
    PRELOAD: { ...NUMBER, max: 3 },
    INITIATION: TOGGLE,
    ATTEMPTED: ATTEMPTED_DATA,
    SCORED: SCORED_DATA,
    "REFUEL FROM:": {
      "C-F TRENCH": TOGGLE,
      "F-F TRENCH": TOGGLE,
      "C-O TRENCH": TOGGLE,
      "F-O TRENCH": TOGGLE,
      RENDEZVOUS: TOGGLE,
      "ALLIANCE PARTNER": TOGGLE,
    },
    "DISPENSE TO ALLIANCE PARTNER:": {
      ...SELECT,
      options: ["ATTEMPTED", "SUCCESSFUL"],
    },
  },
  TELEOP: {
    ATTEMPTED: ATTEMPTED_DATA,
    SCORED: SCORED_DATA,
    "REFUEL FROM:": {
      GROUND: TOGGLE,
      "HIGHER LEVEL BAY": TOGGLE,
    },
    "DISPENSE TO ALLIANCE PARTNER:": {
      ...SELECT,
      options: ["ATTEMPTED", "SUCCESSFUL"],
    },
    "CONTROL PANEL": {
      "POSITION?": TOGGLE,
      "ROTATION?": TOGGLE,
    },
    ENDGAME: {
      LEVEL: { ...SELECT, options: ["PARK", "HANG"], default: "NONE" },
      ASSIST: {
        ...SELECT,
        options: ["WAS ASSISTED", "ASSIST ANOTHER"],
        default: "NONE",
      },
      TIMES: { HOOK: TIMER, LIFT: TIMER },
      "LEVELING?": TOGGLE,
    },
  },
  ATTRIBUTES: {
    OUTTAKE: TOGGLE,
    "UNDER TRENCH": TOGGLE,
    BREAK: TOGGLE,
    TIP: TOGGLE,
    "SUM AUTO": NUMBER,
    "SUM TELE": NUMBER,
  },
};
export default INFINITE_RECHARGE;
